name: Prettier Action

on:
  push:
    branches-ignore: [master, main]
  pull_request:
    branches: [master, main]
  workflow_dispatch:

jobs:
  prettier:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: read
      statuses: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
    
      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write **/*.{js,md,html,css}
