name: Unit Testing

on: 
  pull_request:
  workflow_dispatch:
  push:
  

jobs:
  unit-test:
    name: Run tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
      - name: Run jests
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: npm install
      - name: test
        run: npm test
